# Generated by Django 5.2.7 on 2025-10-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nocode_bench_id', models.CharField(help_text='e.g. example-repo/task-001', max_length=255, unique=True)),
                ('doc_change_input', models.TextField(help_text='The documentation change instruction.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('FAILED_APPLY', 'Failed_Apply'), ('FAILED_TEST', 'Failed_Test')], default='PENDING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_percent', models.FloatField(default=0.0)),
                ('applied_percent', models.FloatField(default=0.0)),
                ('rt_percent', models.FloatField(default=0.0)),
                ('fv_micro', models.FloatField(default=0.0)),
                ('fv_macro', models.FloatField(default=0.0)),
                ('file_percent', models.FloatField(default=0.0)),
                ('num_token', models.IntegerField(default=0)),
                ('generated_patch', models.TextField(help_text='The code patch generated by the LLM.')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='agent_core.evaluationtask')),
            ],
        ),
    ]
